---
spamd_passtime: 2     # delivery can be retried after 2 minutes
spamd_greyexp: 6      # greylisted entries expire after 6 hours
spamd_whiteexp: 2190  # whitelisted entries expire after 3 months

spamd_blacklists:
  nixspam: www.openbsd.org/spamd/nixspam.gz

bigmailers:
  - aliexpress.com
  - amazon.com
  - ebay.com
  - github.com
  - google.com
  - icloud.com
  - kijiji.com
  - linkedin.com
  - mandrillapp.com
  - mailchimp.com
  - microsoft.com
  - outlook.com
  - paypal.com
  - sendgrid.net
  - t-mobile.com
  - verizon.com
  - yahoo.com
  - intuit.com
  - facebookmail.com
