---
- name: create configuration directories
  file:
    path: '{{ item }}'
    state: directory
  with_items:
    - /etc/sites
    - /etc/httpd.d

- name: create sites.conf
  copy:
    content: ''
    dest: /etc/httpd.d/sites.conf
    force: no

- name: generate configuration
  template:
    src: '{{ item.0 }}.j2'
    dest: '{{ item.1 }}/{{ item.0 }}'
  with_together:
    - [ 'httpd.conf', 'http.conf',    'https.conf'   ]
    - [ '/etc',       '/etc/httpd.d', '/etc/httpd.d' ]
  notify: reload httpd

- name: enable daemon
  service:
    name: httpd
    enabled: yes
    state: started

- name: generate configuration for www vhost
  template:
    src: www.conf.j2
    dest: /etc/sites/www.conf
  notify: reload httpd

- name: enable www vhost
  lineinfile:
    path: /etc/httpd.d/sites.conf
    line: include "/etc/sites/www.conf"
