---
- name: get current turn secret
  shell: grep '^turn_shared_secret:' {{ synapse_config_dir }}/homeserver.yaml | awk '{ print $2 }'
  changed_when: False
  failed_when: False
  register: grep_turn_secret

- name: check turn secret
  set_fact:
    turn_secret: '{{ grep_turn_secret.stdout }}'
  when: grep_turn_secret.stdout != ""

- block:
  - name: generate new turn secret
    command: pwgen 64 1
    changed_when: False
    register: pwgen_turn_secret

  - name: set turn secret
    set_fact:
      turn_secret: '{{ pwgen_turn_secret.stdout }}'

  when: grep_turn_secret.stdout == ""

- name: get macaroon secret
  shell: grep '^macaroon_secret_key:' {{ synapse_config_dir }}/homeserver.yaml | awk '{ print $2 }'
  changed_when: False
  failed_when: False
  register: grep_macaroon_secret

- name: check macaroon secret
  set_fact:
    macaroon_secret: '{{ grep_macaroon_secret.stdout }}'
  when: grep_macaroon_secret.stdout != ""

- block:
  - name: generate new macaroon secret
    command: pwgen 64 1
    changed_when: False
    register: pwgen_macaroon_secret

  - name: set macaroon secret
    set_fact:
      macaroon_secret: '{{ pwgen_macaroon_secret.stdout }}'

  when: grep_macaroon_secret.stdout == ""

- name: get registration secret
  shell: grep '^registration_shared_secret:' {{ synapse_config_dir }}/homeserver.yaml | awk '{ print $2 }'
  changed_when: False
  failed_when: False
  register: grep_registration_secret

- name: check registration secret
  set_fact:
    registration_secret: '{{ grep_registration_secret.stdout }}'
  when: grep_registration_secret.stdout != ""

- block:
  - name: generate new registration secret
    command: pwgen 64 1
    changed_when: False
    register: pwgen_registration_secret

  - name: set registration secret
    set_fact:
      registration_secret: '{{ pwgen_registration_secret.stdout }}'

  when: grep_registration_secret.stdout == ""
